version: "3.9"

services:
  frontend:
    image: akshat8630/snapcart-frontend:latest
    container_name: snapcart-frontend
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - snapcart-net
    restart: unless-stopped

  backend:
    image: akshat8630/snapcart-backend:latest
    container_name: snapcart-backend
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    networks:
      - snapcart-net
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: snapcart-mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - snapcart-net
    restart: unless-stopped

networks:
  snapcart-net:
    driver: bridge

volumes:
  mongo-data:
